name: cicd deployment

on:
    push:
        branches:
            - main

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
  secret-scan:
    name: Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #secret-scan:
  #build:
  #push-to-ecr:
  #deploy-to-ec2:
